include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
    library_private_types_in_public_api: false
    no_leading_underscores_for_local_identifiers: false
    prefer_adjacent_string_concatenation: false
    prefer_function_declarations_over_variables: false
    prefer_interpolation_to_compose_strings: false

    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_const_literals_to_create_immutables: false

analyzer:
  exclude: [build/**, lib/generated/**, lib/gen/**]
  plugins:
    # - custom_lint
  errors:
    invalid_annotation_target: ignore

custom_lint:
  rules:
    - missing_provider_scope: false
